# Configuração otimizada para Render
services:
  - type: web
    name: alego-manus
    env: python
    region: oregon # ou sua região preferida
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/debug/health
  - type: web
    name: alego-manus-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://sua-api.render.com
      - key: GENERATE_SOURCEMAP
        value: false
