# Configuração otimizada para Render - Backend + Frontend
services:
  # Backend API (Python/Flask) e Frontend (React Static Site) unificados
  - type: web
    name: alego-manus
    env: python
    buildCommand: |
      cd frontend && npm ci && npm run build
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /api/debug/health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"  # Versão mais específica
      - key: NODE_VERSION
        value: "18.17.0"
      - key: FLASK_ENV
        value: production

# Database PostgreSQL (se necessário)
databases:
  - name: alego-manus-db
    plan: free
    region: oregon
