# DigitalOcean App Platform Configuration
name: alego-manus
region: nyc

# Frontend Service (Static Site) - TESTE SIMPLES
static_sites:
  - name: frontend
    source_dir: /
    github:
      repo: dyuliano14/Alego-manus
      branch: main
      deploy_on_push: true
    index_document: index.html
    error_document: index.html
    routes:
      - path: /

# Backend Service (Python/Flask) - DEPOIS DO FRONTEND
services:
  - name: backend
    source_dir: /backend
    github:
      repo: dyuliano14/Alego-manus
      branch: main
      deploy_on_push: true
    run_command: gunicorn --bind 0.0.0.0:$PORT app:app
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: FLASK_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: FLASK_APP
        value: app.py
        scope: RUN_AND_BUILD_TIME

# Managed PostgreSQL Database
databases:
  - name: alego-db
    engine: PG
    version: "15"
    size: db-s-dev-database
    production: false
